In [1]:
import pandas as pd

In [2]:
data = {
    'city': ['Osaka', 'Tokyo', 'Kyoto', 'Kobe', 'Fukuoka', 'Sapporo', 'Nagoya'],
    'population': [2755, 9716, 1443, 1504, 1538, 1957, 2322],
    'area': [255, 627, 827, 557, 343, 1121, 326]
}
df = pd.DataFrame(data)
# データの表示
print(df)

      city  population  area
0    Osaka        2755   255
1    Tokyo        9716   627
2    Kyoto        1443   827
3     Kobe        1504   557
4  Fukuoka        1538   343
5  Sapporo       11957  1121
6   Nagoya        2322   326